# fly.toml app configuration file generated for creature-radicle on 2024-06-20T16:45:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'creature-radicle'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8776
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
