# fly.toml app configuration file generated for creature-osprey on 2024-07-29T22:17:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'creature-osprey'
primary_region = 'waw'

[build]

[processes]
  app = 'eval `ssh-agent` && rad node start'
  radicle-httpd = 'rc-service radicle-httpd start'
  radicle-ui = 'cd /home/${USER}/radicle-explorer && bun run start'

[[mounts]]
  source = 'radicle_volumes'
  destination = '/home/seed/.radicle/seed'
  initial_size = '1gb'
  processes = ['app']

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['radicle-ui']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['radicle-httpd']

  [[services.ports]]
    port = 8443
    handlers = ['tls']

[[services]]
  protocol = 'tcp'
  internal_port = 8776
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']

  [[services.ports]]
    port = 8776
    handlers = ['tls']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
